services:
  - type: web
    name: cv-creator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production